name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.43.5

      - run: deno fmt --check

      - run: deno lint

      - run: deno test 

      - name: Publish package to jsr.io
        run: deno publish
